apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-tfav
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-tfav
    app.kubernetes.io/part-of: cin4s-839-0013-app
  name: devfile-sample-tfav
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-tfav
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-tfav
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0013-tenant/cin4s-839-0013-app/devfile-sample-tfav@sha256:2ecbfb53886c5e1b9834a34ed4237c69abac820ee8b06565c2a616c65b4a8901
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
